import { PropertyCard } from "./property-card";

const properties = [
  {
    id: 1,
    image: "https://picsum.photos/400/300",
    badge: "Top Villa",
    badgeColor: "bg-orange-500",
    title: "Luxe 1 BDR Romantic hideaway...",
    location: "Top Villa • Self Check-in • Free Reschedule",
    rating: 4.73,
    beds: 1,
    baths: 2,
    guests: 4,
    originalPrice: "$10,000",
    price: "$2,500",
    period: "night",
  },
  {
    id: 2,
    image: "https://picsum.photos/400/300",
    badge: "Top Villa",
    badgeColor: "bg-orange-500",
    title: "BALIAN TREEHOUSE w beautiful...",
    location: "Top Villa • Free Reschedule",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 2,
    price: "$3,700",
    period: "night",
  },
  {
    id: 3,
    image: "https://picsum.photos/400/300",
    title: "Velvana Bali - Owl Bamboo Ho...",
    location: "Instant Book • Self Check-in",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 4,
    price: "$4,500",
    period: "night",
  },
  {
    id: 4,
    image: "https://picsum.photos/400/300",
    title: "Dome - Bamboo Villa in Eco Si...",
    location: "Book Now Pay Later",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 4,
    originalPrice: "$1,000",
    price: "$4,500",
    period: "night",
  },
  {
    id: 5,
    image: "https://picsum.photos/400/300",
    title: "Orca Villa",
    location: "Top Villa • Book Now Pay Later",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 4,
    price: "$8,250",
    period: "night",
  },
  {
    id: 6,
    image: "https://picsum.photos/400/300",
    badge: "Instant Book",
    badgeColor: "bg-red-500",
    title: "Seaside Junior Suite",
    location: "Instant Book",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 4,
    originalPrice: "$9,000",
    price: "$6,000",
    period: "night",
  },
  {
    id: 7,
    image: "https://picsum.photos/400/300",
    badge: "Book Now Pay Later",
    badgeColor: "bg-red-500",
    title: "Villa Hot by musuk villas",
    location: "Book Now Pay Later",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 10,
    price: "$10,000",
    period: "night",
  },
  {
    id: 8,
    image: "https://picsum.photos/400/300",
    title: "Treasure of Bali, 3BR villa, infini...",
    location: "Top Villa",
    rating: 4.73,
    beds: 1,
    baths: 1,
    guests: 6,
    price: "$1,750",
    period: "night",
  },
];

export function PropertyGrid() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 sm:gap-6">
      {properties.map((property) => (
        <PropertyCard key={property.id} property={property} />
      ))}
    </div>
  );
}
